### ISSUE TITLE
Support for older python versions

### ISSUE THREAD

**Issue by jannisborn** [dylanwal/BigSMILES#4]
Hi @dylanwal,

Interesting library, thanks for developing! What's the reason/blocker for not supporting older python versions than 3.10? Currently, not even 3.7 has reached EOL.

**Comment by dylanwal** [comment]
Thanks for bring this to my attention! The limitation is mainly because I am using the new type hinting features of 3.10, but I will look at adapting it so it can run on 3.7 in the next update which should be later this week. I will post an update here when its ready.

**Comment by jannisborn** [comment]
Great to hear :)

**Comment by dylanwal** [comment]
Package updated and tested against python 3.7
